"""create date default

Revision ID: 2cac651304a0
Revises: ebce642be5a9
Create Date: 2023-02-16 18:03:22.937667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cac651304a0'
down_revision = 'ebce642be5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
