"""create date default

Revision ID: 430a0db72595
Revises: 9cc1ad3c8a78
Create Date: 2023-02-16 17:53:02.427144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430a0db72595'
down_revision = '9cc1ad3c8a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
