"""Added close_date field

Revision ID: 610996988ace
Revises: f8a6fdcfd02d
Create Date: 2023-02-12 21:50:19.257548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610996988ace'
down_revision = 'f8a6fdcfd02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('close_date')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('close_date')

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_column('close_date')

    # ### end Alembic commands ###
