"""new base in models module

Revision ID: 67789b377234
Revises: 6ef6436178fb
Create Date: 2023-02-18 20:33:41.530989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67789b377234'
down_revision = '6ef6436178fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
