"""deleted fields from User model

Revision ID: 9cc1ad3c8a78
Revises: 610996988ace
Create Date: 2023-02-16 17:38:28.177376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc1ad3c8a78'
down_revision = '610996988ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('invested_amount')
        batch_op.drop_column('full_amount')
        batch_op.drop_column('fully_invested')
        batch_op.drop_column('close_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('close_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fully_invested', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('full_amount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('invested_amount', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
