"""create date default

Revision ID: ebce642be5a9
Revises: 15ef182976ba
Create Date: 2023-02-16 18:01:42.261334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebce642be5a9'
down_revision = '15ef182976ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
