"""db rename

Revision ID: fbf7ea099b24
Revises: 67789b377234
Create Date: 2023-03-03 16:09:34.042642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf7ea099b24'
down_revision = '67789b377234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
